name: feedmypooch
favicon: null
layout_spectrum: 0.52017
typography_spectrum: 0.61831
title: Feed My Pooch
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#cfdade'
    - '#a2af5f'
    - '#6a771f'
    - '#593a35'
    - '#070110'
  brandStrength: 0.1875
  lightness: 0.25
  saturation: 0.45978631754405797
  rhythmicContrast: 0.8433675451669842
purpose: []
