name: feedmypooch
favicon: null
layout_spectrum: 1
typography_spectrum: 0.8229
title: Feed My Pooch
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#332c1a'
    - '#645e44'
    - '#f1c177'
    - '#ffffff'
    - '#fcec00'
  brandStrength: 0.1875
  lightness: 0.25
  saturation: 0.45978631754405797
  rhythmicContrast: 0.8433675451669842
purpose: []
